### ISSUE TITLE
Use sessions in place of global variables

### ISSUE THREAD

**Issue by roshnet** [parisnakitakejser/socketchat-server#1]
@parisnakitakejser Based on my limited understanding of this code base, I think it would be a nice idea to store variables like `users_online` and `guest_vistor_count` in a session variable. This prevents the variables being reset on a page reload.

**Comment by parisnakitakejser** [comment]
Thanks for you feedback, its will coming but first i will add support for database (MongoDB) i will ofc record this and published it.

i will keep you updated on this issue/featuer :)
